using System;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;

namespace CurriculumVitae.Helpers
{
	public class EmailHelper
	{
        private const string OutlookSmtp = "smtp-mail.outlook.com";
        private const string EmailAddressFrom = "your_email_address@mail.com";
        private const string EmailSubject = "Curriculum Vitae";
        private static string EmailBodyTemplate = 
            $"Hello," +
            $"{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"Thanks for using 'Curriculum Vitae' services. This email contains your CV generated by out website. " +
            $"{Environment.NewLine}" +
            $"Wish you the best of luck on your interviews!" +
            $"{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"Best Regards!" +
            $"{Environment.NewLine}" +
            $"Team 'Curriculum Vitae'";
        private const string Password = "password";
        private const int SecuredPort = 587;

        public static async Task<bool> SendEmailAsync(string emailAddressTo, string filePath)
		{
            var emailSend = false;
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient SmtpServer = new SmtpClient(OutlookSmtp);
                Attachment file = new Attachment(filePath);

                mail.From = new MailAddress(EmailAddressFrom);
                mail.To.Add(emailAddressTo);
                mail.Subject = EmailSubject;
                mail.Body = EmailBodyTemplate;
                mail.Attachments.Add(file);

                SmtpServer.UseDefaultCredentials = false;
                SmtpServer.Credentials = new NetworkCredential(EmailAddressFrom, Password);
                SmtpServer.Port = SecuredPort;
                SmtpServer.EnableSsl = true;

                await SmtpServer.SendMailAsync(mail);

                emailSend = true;
            }
            catch (Exception)
            { }

            return emailSend;
        }
	}
}
